#!/bin/bash
#SBATCH --job-name=CDS_extraction             # Job name for Slurm
#SBATCH --output=/home/barrientosm/scratch/CDS_sequences/log_%j_%x_out.txt         # Log file for standard output (job ID and name included)
#SBATCH --error=/home/barrientosm/scratch/CDS_sequences/log_%j_%x_err.txt          # Log file for standard error (job ID and name included)
#SBATCH --nodes=1                            # Number of nodes to use
#SBATCH --ntasks-per-node=1                  # Number of tasks per node
#SBATCH --mem=6G                             # Memory allocation per job
#SBATCH --time=1:00:00                       # Time limit for the job
#SBATCH --partition=agap_long                # Specify the job queue/partition

# -------------------------------------------------------------------------------
# README - Extraction of mRNA Sequences and Adjacent Regions  
# -------------------------------------------------------------------------------
# Description:  
# This script uses the AGAT tool to extract CDS sequences from a GFF file and a reference genome.  
# CDS: portion of genes translated in proteins

# -------------------------------------------------------------------------------
# Step 1: Load required modules
# -------------------------------------------------------------------------------
module load bioinfo-cirad                     # Load the bioinformatics module
module load AGAT/1.2.0-singularity            # Load the AGAT tool module (version 1.2.0)

# -------------------------------------------------------------------------------
# Step 2: Define file paths
# -------------------------------------------------------------------------------

# Path to the directory containing GFF files
gff_path="/home/barrientosm/scratch/angsd_analysis/urartu/samtool_GL/tajima_no_soft_clipped_reads"

# Specific GFF file to use (modified version)
gff_file="$gff_path/Triticum_urartu.IGDB.59.chr.gff3"

# Path to the directory containing FASTA genome files
Genome_path="/home/barrientosm/projects/GE2POP/REFERENCES/TRITICUM/URARTU_ORIGINAL"

# Reference genome FASTA file (modified version)
Genome="$Genome_path/Triticum_urartu.IGDB.dna.toplevel.fa"

# output directory
output_dir="/home/barrientosm/scratch/CDS_sequences/urartu"

# -------------------------------------------------------------------------------
# Step 3: Extract mRNA sequences with AGAT
# -------------------------------------------------------------------------------
# The AGAT command extracts mRNA sequences and includes 200 bp upstream and downstream regions.
# Flags:
#   -g: Path to the GFF file.
#   -f: Path to the genome FASTA file.
#   -t: Type of feature to extract.
#   -o: Output file to store the extracted sequences.

agat_sp_extract_sequences.pl \
    -g $gff_file \
    -f $Genome \
    -t cds \
    -o $output_dir/speltoides_full_CDS.fasta

# -------------------------------------------------------------------------------
# Output:
# The extracted CDS sequences
# regions, are saved in the file: "speltoides_full_CDS.fasta".
# -------------------------------------------------------------------------------
